Treat only StdLib Ruby files as stable.
This fixes test failure on Fedora:

~~~
  1) Error:
Bootsnap::LoadPathCache::PathTest#test_stability:
NoMethodError: undefined method `pry' for #<Binding:0x00007f34f6608c90>
    /builddir/build/BUILD/bootsnap-1.15.0/usr/share/gems/gems/bootsnap-1.15.0/test/load_path_cache/path_test.rb:25:in `test_stability'
~~~

where the culprit is that Ruby StdLib lives in `/usr/share`, instead of
`/usr/lib64`. However, given Ruby flexible configuration this needs to
be correctly handled.

As it seems, that the real intention always was to consider just Ruby
StdLib as stable, because otherwise, there would not be exception for
Site dir. Therefore, cover just the StdLib via
`RbConfig::CONFIG["rubylibdir"]` and `RbConfig::CONFIG["rubyarchdir"]`
and treat everything else as unstable.

Fixes #431